name: Build and Tag Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Commit SHA
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and Tag Docker Image
        run: |
          IMAGE_NAME=$DOCKER_HUB_NAMESPACE/$REPOSITORY_NAME_PART:${{ env.COMMIT_SHA }}
          docker build -t $IMAGE_NAME .
  deploy:
    runs-on: self-hosted
    needs: [build]
    steps:
    - name: change image name
      run: |
        sed -i '/interlink_backend:/,/image:/s|\(image: \S*\):[^ ]*|\1:${{ env.IMAGE_NAME }}|' text.txt
      
