name: Build and Tag Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_NAMESPACE: hoangcn
  REPOSITORY_NAME_PART: hoangcn
  
jobs:
  build:
    runs-on: self-hosted
    outputs:
      image_name: ${{ steps.builds.outputs.IMAGE_NAME }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Commit SHA
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        
      - name: Set github env image name
        id: builds
        run: echo "IMAGE_NAME=$(echo $DOCKER_HUB_NAMESPACE/$REPOSITORY_NAME_PART:${{ env.COMMIT_SHA }})" >> $GITHUB_OUTPUT

      - name: Build and Tag Docker Image
        run: docker build -t $IMAGE_NAME -f Dockerfile .
  deploy:
    runs-on: self-hosted
    needs: [build]
    env:
      IMAGE_NAME: ${{ needs.build.outputs.image_name }}
    steps:
    - name: test env image name
      run: echo ${{ env.IMAGE_NAME }}
      
    - name: change image name
      run: |
        sed -i "/interlink_backend:/,/image:/s/\(image:\s*\)[^ ]*/\1${{ env.IMAGE_NAME }}/" text.txt
      
