name: Build and Tag Docker Image

on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: self-hosted
    env:
      DOCKER_HUB_NAMESPACE: hoangcn
      REPOSITORY_NAME_PART: hoangcn
    outputs:
      image_name: ${{ steps.builds.outputs.IMAGE_NAME_OUTPUT }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Commit SHA
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        
      - name: Set github env image name
        id: builds
        run: |
          echo "IMAGE_NAME_OUTPUT=$(echo $DOCKER_HUB_NAMESPACE/$REPOSITORY_NAME_PART:${{ env.COMMIT_SHA }})" >> $GITHUB_OUTPUT

      - name: Build and Tag Docker Image
        run: docker build -t ${{ steps.builds.outputs.IMAGE_NAME_OUTPUT }} -f Dockerfile .
        
  deploy:
    runs-on: self-hosted
    needs: [build]
    env:
      IMAGE_NAME_OUTPUT: ${{ needs.build.outputs.image_name }}
    steps:
    - name: change image name
      run: |
        ESCAPED_IMAGE_NAME=$(printf '%s\n' "${{ env.IMAGE_NAME_OUTPUT }}" | sed 's/[\/&]/\\&/g')
        sed -i "/interlink_backend:/,/image:/s/\(image:\s*\)[^ ]*|\1$ESCAPED_IMAGE_NAME|" text.txt
      
